### ISSUE TITLE
Basic billing process

### ISSUE THREAD

**Issue by qdequele** [meilisearch/product#235]
# Context
In order to open Meilisearch Cloud to companies, it is necessary to allow these companies to pay. 

# Objective
This first issue aims to offer the user a simple flow that allows him to enter his credit card, subscribe to one of our offers, retrieve these invoices. 

# Ressources
- [Design](https://www.figma.com/file/9GA8LomQgcbKiozYhgxa0C/SaaS-Interfaces?node-id=195%3A4197) 

Pricing Table:
<table>
	  <thead>
		    <tr>
			    <th>RAM (GB)</th>
			    <th>vCPU</th>
			    <th>Disk</th>
			    <th>Hourly Price</th>
		    </tr>
	  </thead>
	  <tbody>
		    <tr>
			    <td>1</td>
			    <td>0.5</td>
			    <td>10</td>
			    <td>$0.04</td>
		    </tr>
		    <tr>
			    <td>4</td>
			    <td>1</td>
			    <td>40</td>
			    <td>$0.17</td>
		    </tr>
		    <tr>
			    <td>16</td>
			    <td>4</td>
			    <td>160</td>
			    <td>$0.64</td>
		    </tr>
		    <tr>
			    <td>64</td>
			    <td>16</td>
			    <td>640</td>
			    <td>$2.56</td>
		    </tr>
	  </tbody>
</table>

# Todo

### Design
- [x] Design the billing flow in the Meilisearch cloud

### Dev
- [x] https://github.com/meilisearch/meilisearch-cloud/issues/399
- [x] https://github.com/meilisearch/meilisearch-cloud/issues/396

**Comment by qdequele** [comment]
Link to feature: https://meilisearch.productboard.com/feature-board/planning/features/9562675
