### ISSUE TITLE
Having a clear URL for a project

### ISSUE THREAD

**Issue by qdequele** [meilisearch/product#399]
# Context
Today we have an issue with our actual project URLs. They are built like `ms-{uuid}.saas.meili.dev`. This way, URLs are not:
- Available: `meili.dev` doesn't have a great resolve speed across the world.
- Predictable/Memorizable: having a UUID in the URL doesn't help to keep this URL in mind. 

# Goal
Our main goal is to find an URL format that is **available**, **predictable** and **memorizable**.

# Problems exploration

### Problem: Availability

A user needs an URL to contact its server. Until now, we have proposed an URL built like `ms-{uuid}.saas.meili.dev`.
This URL will be pushed in production on the user frontend, backend, and sometimes mobile.
We should be sure that this URL will always be available and not change. 

### Problem: Future Serverless

In the future, a project will probably be split into two parts. The indexation and the search. Is it possible to keep both services under one URL?

### Problem: Environment

A user could need to have several environments for the same project. Some of our users already use the classic Prod/Staging/Dev environment. How should we handle both three environments?

### Problem: Memorization

A user would like to understand what this URL is. If the URL is non-sense, it’s not dramatic, but it will not be memorizable, and it will affect the user experience on the solution. Having well-constructed URL help people to understand and add a predictability impression. 

### Problem: Security

It could bring security issues if the URL is too predictable. anyone can try to find the URL from another company in order to damage its search. 

# What is the problem to fix

Among the problems mentioned above, I think that the problems with the most impact are the problem of **availability** and **memorization**. 

We don’t choose the **future serverless** issue because it will come in the future, we could keep it in mind, but we don’t want to solve a problem we don’t have today. 

We also don’t choose the **environment** issue because it will not affect users now and should be considered in a proper discovery process. 

The **security** issue doesn’t really exist. In fact, we don't care because the search is either open and anyone can retrieve it with `inspect the element` or it is protected by a token.

# Potential solutions

## URL format

- `{project_uid}.{domain_name}`
	It will be a long text, it’s not easy to read, not easy to memorize. 
    
- `{project_slug}.{domaine_name}`
	much simpler to read and to memorize but it could be difficult to use in real life because we will have to make unique the project_slug and it could be frustrating for the user. 
    
- `{project_name}-{random_text}.{domain_name}`
	One solution for the previous issue is to add a random text at the end of the project url. Could be good but the random text has to be memorizable. Some example:
    - `[movies-hso3nc.meili.dev](http://movies-hso3nc.meili.dev)` → difficult to memorize red ❌
    - `[movies-1.meili.dev](http://movies-1.meili.dev)` → easy to memorize but a bit weird. ❌
    - `[movies-flamand.meili.dev](http://movies-flamand.meili.dev)` → easy to memorize and secure ✅
    
- `{project_slug}-{user_slug}.{domain_name}`
    This solution is perfect because it is memorizable and unique. The only issue is to create a `user_slug` for every user. 
    
> 💡 What is a slug? We use it for `project_slug` and `user_slug`. A slug is a sequence of unique characters that identifies an entity. Unlike an Id or UUID, the slug is often used to describe a sentence with meaning. A nickname, the name of a project. It can contain letters, numbers, and the following special characters `.-_`. Here is an example of how Github is doing.
> ![Screenshot 2022-02-15 at 18.28.03.jpg](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/7707a885-0507-493f-8e53-37bde279773d/Screenshot_2022-02-15_at_18.28.03.jpg)

## Domain name

We have multiple possible domain names, we will choose the one with the better DNS benchmark. 

- `meilisearch.io`: This domain name has the best DNS Speed all over the world so I believe we will choose this one. Moreover, this TLD is maintained by Google so we can trust them in terms of uptime. [meilisearch.io benchmark](https://user-images.githubusercontent.com/6064892/155376128-841c217f-d382-4e70-9e1d-e903dac2061b.png)
    
- `meilisearch.org`: Unfortunately, this domain name doesn’t have a great ping on Asia. [meilisearch.org benchmark](https://user-images.githubusercontent.com/6064892/155376165-5dc27cb6-43a7-4cf3-9691-84062945df8a.png)
    
- `meilisearch.cloud`: Unfortunately, this domain name is not good at all in many countries. [meilisearch.cloud benchmark](https://user-images.githubusercontent.com/6064892/155376185-98001d6e-ec09-4a22-9946-2188bebca6ab.png)
    
- `meilisearch.dev`: Bad in a lot of country. [meilisearch.dev benchmark](https://user-images.githubusercontent.com/6064892/155376201-0d7fb96b-f6fb-418c-823c-6f3aac5375be.png)

## Subdomain for cluster location

Removing the server position in the URL is currently a challenge for the Tech team. It could be something challenged in the future to improve the global URL readability but today it seems impossible to do. 

The URLs will have to have as subdomain the cluster location. The naming convention will follow the `cluster_slug` used by the provider [Digital Ocean](https://docs.digitalocean.com/products/platform/availability-matrix/#available-datacenters), [AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#using-regions-availability-zones-describe), [GCP](https://cloud.google.com/compute/docs/regions-zones) or [Azure](https://azuretracks.com/2021/04/current-azure-region-names-reference/). 

## Adding its own domain

The company could add their own domain names and it will allow them to add restrictions on their website on the host origin. It also could help to add security thanks to the CORS or other mechanisms. 

## Having multiple URLs for a project

No matter how much focus we put on this process we will have to propose several URLs to the user at one time or another. Whether it's because the user wants to use his own URL or because we have to switch from legacy URLs to new ones, we will absolutely have to display several URLs for the same project at one time or another. 

# Final solutions

I would suggest two things, first and I think it should be enough for the first iteration, I would suggest this URL schema:
`{project_slug}-{user_slug}.{cluster_slug}.meilisearch.io`. 

The domain name, [meilisearch.io](http://meilisearch.io) has a TLD that has good performances and good uptime. 

I would suggest allowing people to add their own domain name in a second time. It should not be so complex to do and could have real benefits for big companies.

However, we still need to consider the possibility of displaying multiple URLs for a single project. 

# Todo
### Dev
- [x] https://github.com/meilisearch/meilisearch-cloud/issues/391
- [x] https://github.com/meilisearch/meilisearch-cloud/issues/764

### Design
- [x] meilisearch/design-team#24

## Second Iteration:
- [ ] Include on the cloud design the project_slug and the user_slug
- [ ] Introduce int the cloud a project_slug and a user_slug

## Third Iteration:
- [ ] Remove the cluster indication on the project URLs
- [ ] Benchmark the [Cloudflare DNS Provider solution](https://www.cloudflare.com/ssl-for-saas-providers/).

**Comment by qdequele** [comment]
@nicolasvienot I finally updated this issue to mention the possibility to have multiple URLs for the same project. I assume that this is a behavior brought by the solution to the user problem present in this issue.

**Comment by nicolasvienot** [comment]
@qdequele I created a tracking issue for Tech [here](Show multiple URLs for the same project) that you can use.

**Comment by qdequele** [comment]
@nicolasvienot the design is finished. https://github.com/meilisearch/design-team/issues/24

**Comment by davelarkan** [comment]
Closing – the linked tracking issue for the tech team is complete
